spring:
  profiles:
    active: local

logging:
  file:
    name: logs/bookstore.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 7
      file-name-pattern: logs/bookstore.%d{yyyy-MM-dd}.%i.log
